[project]
name = "orange-sherbert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==5.0",
    "django-htmx>=1.27.0",
    "django-template-partials>=25.3",
    "playwright>=1.56.0",
]
